### ISSUE TITLE
Suggestion: By default stop inheritance when reaching root

### ISSUE THREAD

**Issue by adelavega** [cmi-dair/bids2table#15]
https://github.com/cmi-dair/bids2table/blob/886d184bd28d937dc9fc9ec6531c31add343dccd/bids2table/extractors/_inheritance.py#L23

I might suggest making the default stopping rule finding the `dataset_description.json` file rather than 4 levels of depth, which could cause errors in some datasets.

**Comment by clane9** [comment]
Sounds good, thanks for the suggestion!
